# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('area_of_specialization', models.CharField(max_length=200)),
                ('no_of_publication', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('phd_student_guided', models.CharField(max_length=200)),
                ('mtech_student_guided', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
