# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 04:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20160107_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_announcement',
            field=models.CharField(default=datetime.datetime(2016, 1, 7, 4, 54, 3, 344793, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='author_events',
            field=models.CharField(default=datetime.datetime(2016, 1, 7, 4, 54, 9, 280454, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='created_date_announcement',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='created_date_events',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='text_announcement',
            field=models.TextField(default=datetime.datetime(2016, 1, 7, 4, 54, 11, 740955, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text_events',
            field=models.TextField(default=datetime.datetime(2016, 1, 7, 4, 54, 14, 31210, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title_announcement',
            field=models.CharField(default=datetime.datetime(2016, 1, 7, 4, 54, 20, 480997, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title_events',
            field=models.CharField(default=datetime.datetime(2016, 1, 7, 4, 54, 22, 933345, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
