# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20160107_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_highlights',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_highlights',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
