# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_auto_20160107_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date_announcement',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date_events',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date_highlights',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date_notice',
            field=models.DateTimeField(blank=True),
        ),
    ]
