# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_auto_20160107_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_image',
            field=models.ImageField(default=datetime.datetime(2016, 1, 7, 16, 1, 58, 780414, tzinfo=utc), upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='event_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='event_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='gallery_image',
            field=models.ImageField(default=datetime.datetime(2016, 1, 7, 16, 2, 2, 266096, tzinfo=utc), upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slide_image1',
            field=models.ImageField(default=datetime.datetime(2016, 1, 7, 16, 2, 5, 132148, tzinfo=utc), upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slide_image2',
            field=models.ImageField(default=datetime.datetime(2016, 1, 7, 16, 2, 7, 332449, tzinfo=utc), upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slide_image3',
            field=models.ImageField(default=datetime.datetime(2016, 1, 7, 16, 2, 10, 14084, tzinfo=utc), upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='vision_author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='vision_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_announcement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_events',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_notice',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_announcement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_events',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_notice',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_announcement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_events',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_notice',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
