# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_auto_20160108_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date_highlights',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
