# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0009_auto_20160108_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date_highlights',
        ),
    ]
