# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('dept_history', models.TextField()),
                ('infra', models.TextField()),
                ('labs', models.TextField()),
                ('hostel', models.TextField()),
            ],
        ),
    ]
